// Copyright (c) 2025 LucX-UI Project.
// Licensed under the PolyForm Noncommercial License 1.0.0.
// LucX-UI Component. Free for personal and educational use.
// Commercial use (including VPN resale) requires explicit written permission from the author.
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

package awg

import (
	"bytes"
	"fmt"
	"text/template"
)

// TemplateData holds variables for PostUp/PostDown script rendering.
type TemplateData struct {
	AWGInterface   string
	TUNInterface   string // tun0
	AWGServerIP    string
	AWGSubnet      string
	AWGPort        int
	SOCKS5Port     int // SOCKS5 proxy port (child inbound)
	RouteTable     string
	RouteTableName string
	RoutePref      int
	MTU            int
}

const postUpTemplate = `#!/bin/bash
set -e
# LUCX-AWG-ROUTING: PostUp for {{.AWGInterface}} -> tun2socks -> SOCKS5:{{.SOCKS5Port}}
# Generated by LucX-UI — do not edit manually.

# --- Idempotent interface creation ---
ip link add {{.AWGInterface}} type amneziawg 2>/dev/null || true
ip addr add {{.AWGServerIP}}/24 dev {{.AWGInterface}} 2>/dev/null || true
ip link set {{.AWGInterface}} mtu {{.MTU}}
ip link set {{.AWGInterface}} up

# LUCX-AWG-ROUTING: Kernel forwarding
sysctl -w net.ipv4.ip_forward=1 -q

# LUCX-AWG-ROUTING: tun0 for tun2socks
ip tuntap add dev {{.TUNInterface}} mode tun 2>/dev/null || true
ip addr add {{.AWGServerIP}}/24 dev {{.TUNInterface}} 2>/dev/null || true
ip link set {{.TUNInterface}} mtu {{.MTU}}
ip link set {{.TUNInterface}} up

# LUCX-AWG-ROUTING: tun2socks bridge (AWG traffic -> SOCKS5 proxy)
pkill -f "tun2socks -device {{.TUNInterface}}" 2>/dev/null || true
tun2socks -device {{.TUNInterface}} -proxy socks5://127.0.0.1:{{.SOCKS5Port}} -loglevel silent &
sleep 1

# LUCX-AWG-ROUTING: Policy routing for AWG subnet
ip rule add from {{.AWGSubnet}} table {{.RouteTable}} pref {{.RoutePref}} 2>/dev/null || true
ip route add default dev {{.TUNInterface}} table {{.RouteTable}} 2>/dev/null || true

# LUCX-AWG-ROUTING: nftables (idempotent — delete before create)
nft delete table ip awg_nat 2>/dev/null || true
nft add table ip awg_nat
nft add chain ip awg_nat postrouting { type nat hook postrouting priority 100 \; }
nft add rule ip awg_nat postrouting ip saddr {{.AWGSubnet}} oifname {{.TUNInterface}} masquerade
nft add chain ip awg_nat forward { type filter hook forward priority 0 \; }
nft add rule ip awg_nat forward iifname {{.AWGInterface}} oifname {{.TUNInterface}} accept
nft add rule ip awg_nat forward iifname {{.TUNInterface}} oifname {{.AWGInterface}} ct state related,established accept
`

const postDownTemplate = `#!/bin/bash
set +e
# LUCX-AWG-ROUTING: PostDown for {{.AWGInterface}}
# Generated by LucX-UI — do not edit manually.

# LUCX-AWG-ROUTING: Remove nftables
nft delete table ip awg_nat 2>/dev/null || true

# LUCX-AWG-ROUTING: Remove policy routing
ip route del default dev {{.TUNInterface}} table {{.RouteTable}} 2>/dev/null || true
ip rule del from {{.AWGSubnet}} table {{.RouteTable}} pref {{.RoutePref}} 2>/dev/null || true

# LUCX-AWG-ROUTING: Kill tun2socks
pkill -f "tun2socks -device {{.TUNInterface}}" 2>/dev/null || true
sleep 0.5

# LUCX-AWG-ROUTING: Remove tun0
ip link delete {{.TUNInterface}} 2>/dev/null || true

# LUCX-AWG-ROUTING: Remove AWG interface
ip link del {{.AWGInterface}} 2>/dev/null || true

# LUCX-AWG-ROUTING: Clean up route table entry
sed -i '/^{{.RouteTable}} {{.RouteTableName}}$/d' /etc/iproute2/rt_tables 2>/dev/null || true
`

func RenderPostUp(data TemplateData) (string, error) {
	return renderTemplate("PostUp", postUpTemplate, data)
}

func RenderPostDown(data TemplateData) (string, error) {
	return renderTemplate("PostDown", postDownTemplate, data)
}

func renderTemplate(name, tmpl string, data TemplateData) (string, error) {
	t, err := template.New(name).Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("parse template %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template %s: %w", name, err)
	}
	return buf.String(), nil
}
