// Copyright (c) 2025 LucX-UI Project.
// Licensed under the PolyForm Noncommercial License 1.0.0.
// LucX-UI Component. Free for personal and educational use.
// Commercial use (including VPN resale) requires explicit written permission from the author.
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

package awg

import (
	"bytes"
	"fmt"
	"text/template"
)

// TemplateData holds variables for PostUp/PostDown script rendering.
type TemplateData struct {
	AWGInterface   string
	TUNInterface   string
	AWGServerIP    string
	AWGSubnet      string
	AWGPort        int
	RouteTable     string
	RouteTableName string
	RoutePref      int
	MTU            int
}

// postUpTemplate is fully idempotent — every operation uses 2>/dev/null || true
// or checks before adding (-C). Safe to run multiple times.
const postUpTemplate = `#!/bin/bash
set -e
# LUCX-AWG-ROUTING: PostUp for {{.AWGInterface}} -> {{.TUNInterface}}
# Generated by LucX-UI — do not edit manually.

# --- Idempotent interface creation ---
ip link add {{.AWGInterface}} type amneziawg 2>/dev/null || true
ip addr add {{.AWGServerIP}}/24 dev {{.AWGInterface}} 2>/dev/null || true
ip link set {{.AWGInterface}} mtu {{.MTU}}
ip link set {{.AWGInterface}} up

# LUCX-AWG-ROUTING: Kernel forwarding
sysctl -w net.ipv4.ip_forward=1 >/dev/null

# LUCX-AWG-ROUTING: TUN interface always up with correct MTU
ip link set {{.TUNInterface}} mtu {{.MTU}} 2>/dev/null || true
ip link set {{.TUNInterface}} up 2>/dev/null || true

# LUCX-AWG-ROUTING: Policy routing (idempotent — rule/route add || true)
ip rule add from {{.AWGSubnet}} table {{.RouteTable}} pref {{.RoutePref}} 2>/dev/null || true
ip route add default dev {{.TUNInterface}} table {{.RouteTable}} 2>/dev/null || true

# LUCX-AWG-ROUTING: Firewall (check before add — idempotent)
iptables -C FORWARD -i {{.AWGInterface}} -o {{.TUNInterface}} -j ACCEPT 2>/dev/null || \
  iptables -A FORWARD -i {{.AWGInterface}} -o {{.TUNInterface}} -j ACCEPT
iptables -C FORWARD -i {{.TUNInterface}} -o {{.AWGInterface}} -j ACCEPT 2>/dev/null || \
  iptables -A FORWARD -i {{.TUNInterface}} -o {{.AWGInterface}} -j ACCEPT
iptables -t nat -C POSTROUTING -s {{.AWGSubnet}} -o {{.TUNInterface}} -j MASQUERADE 2>/dev/null || \
  iptables -t nat -A POSTROUTING -s {{.AWGSubnet}} -o {{.TUNInterface}} -j MASQUERADE
`

// postDownTemplate cleans up everything PostUp created.
// All operations use 2>/dev/null || true — safe to run even if partially cleaned.
const postDownTemplate = `#!/bin/bash
set +e
# LUCX-AWG-ROUTING: PostDown for {{.AWGInterface}}
# Generated by LucX-UI — do not edit manually.

# LUCX-AWG-ROUTING: Remove firewall rules
iptables -t nat -D POSTROUTING -s {{.AWGSubnet}} -o {{.TUNInterface}} -j MASQUERADE 2>/dev/null || true
iptables -D FORWARD -i {{.AWGInterface}} -o {{.TUNInterface}} -j ACCEPT 2>/dev/null || true
iptables -D FORWARD -i {{.TUNInterface}} -o {{.AWGInterface}} -j ACCEPT 2>/dev/null || true

# LUCX-AWG-ROUTING: Remove policy routing
ip route del default dev {{.TUNInterface}} table {{.RouteTable}} 2>/dev/null || true
ip rule del from {{.AWGSubnet}} table {{.RouteTable}} pref {{.RoutePref}} 2>/dev/null || true

# LUCX-AWG-ROUTING: Destroy AWG interface
ip link del {{.AWGInterface}} 2>/dev/null || true

# LUCX-AWG-ROUTING: Clean up route table entry
sed -i '/^{{.RouteTable}} {{.RouteTableName}}$/d' /etc/iproute2/rt_tables 2>/dev/null || true
`

func RenderPostUp(data TemplateData) (string, error) {
	return renderTemplate("PostUp", postUpTemplate, data)
}

func RenderPostDown(data TemplateData) (string, error) {
	return renderTemplate("PostDown", postDownTemplate, data)
}

func renderTemplate(name, tmpl string, data TemplateData) (string, error) {
	t, err := template.New(name).Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("parse template %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template %s: %w", name, err)
	}
	return buf.String(), nil
}
